### ISSUE TITLE
Release to Hex.pm

### ISSUE THREAD

**Issue by Havvy** [whatyouhide/short_maps#4]
This is something that works. And while it's not my favourite syntax, it's still better than %{x: x, y: y, z: z, ...}. So apropos for making something that works.

Please release it to Hex.pm (preferably at version 1.0.0), so that for those who would otherwise have this be the only `git` dependency, they would not have to rely upon git.

**Comment by whatyouhide** [comment]
@Havvy just released short_maps on hex, https://hex.pm/packages/short_maps. I released version `0.1.0` so that we have space for some breaking changes before 1.0.0. I'd like for people to use it some more before going 1.0.0.
