### ISSUE TITLE
Unable to refer to struct with same name as module

### ISSUE THREAD

**Issue by Havvy** [whatyouhide/short_maps#7]
E.g. this doesn't work.

``` elixir
defmodule X do
  import ShortMaps

  defstruct [a: nil]

  def foobar(~m{%X a}) do
    a
  end
end
```

**Comment by whatyouhide** [comment]
@Havvy the implementation of structs is broken because it makes bad assumptions :( I'll try to fix it when I got some time :+1: 

/cc @jwarlander

**Comment by jwarlander** [comment]
The proposed changes should make the struct name resolve to the proper module within the context of the caller :) For convenience (because I use the syntax myself sometimes when working within the module of the struct), I made sure it works as `~m{%__MODULE__ a}` as well.
